### ISSUE TITLE
Invalid CSRF Token

### ISSUE THREAD

**Issue by felixfrischeisen** [engelsystem/engelsystem#1274]
Whatever I do, I always get the same - Das angegebene CSRF Token ist ungültig oder abgelaufen - Error.
I have tried multiple Ubuntu 22.04 and 23.04 clean and not clean installs
tried not using docker tried using different versions of docker
tried using external databases

everything goes fine - migrate works but same error every time

nothing worked - can you help me?

**Comment by MyIgel** [comment]
@felixfrischeisen hi, how was the engelsystem installed? (local dev env, some hosting provider, your server, etc)? Is it accessed over http or https ? which browser where you using?
The error normally means that for some reason the cookie is not sent back and thus the token can't be validated.

**Comment by felixfrischeisen** [comment]
@MyIgel I have installed it on my strato VPS and my local Ubuntu Machine (ESXi). Ive tried Safari, Chrome, Firefox. Communication worked over https. Is there a need for a valid SSL Certificate?

**Comment by chipuni** [comment]
I have had the same problem with Amazon servers.

Here's the full details on installation:

Steps for replication:

    Go to AWS, then EC2, then Instances. Launch an instance.

1a. Give it any name.

1b. Choose "Ubuntu Server 22.04 LTS (HVM), SSD Volume Type" as the Amazon Machine Image.

1c. Architecture: 64-bit (x86)

1d. Instance type: t2.micro (free tier eligible)

1e. Use a security group that allows TCP port 22 and 5080 traffic from the Internet.

1f. Configure storage with 30 GiB gp2 root volume, not encrypted.

1g. Launch the instance.

Step 2: Setting up the server.
2a. ssh into your server. For me, this was ssh -i Private/Engelsystem_Key_Pair.pem ubuntu@ec2-44-211-45-77.compute-1.amazonaws.com
2b. In order to install docker, you need to update the software in your system. Here are the steps:

$ sudo apt-get update
$ sudo apt-get upgrade

Accept all defaults.

$ sudo apt-get install docker docker.io docker-compose

Accept all defaults.

$ sudo usermod -a -G docker ubuntu

$ sudo reboot

Log back into the system.

Check that you have docker permission by typing docker ps.

    Load and start Engelsystem:Type the following:

$ git clone https://github.com/engelsystem/engelsystem.gitg

$ cd engelsystem/docker

$ docker-compose build

$ docker-compose up &

$ docker-compose exec es_server bin/migrate

You now have a stock Engelsystem running. Open a http web browser to port 5080 of your machine -- for example,

The default user/password is:

"admin" / "asdfasdf" Enter those into the web browser. You will see the screen with "The provided CSRF token is invalid or has expired."

**Comment by MyIgel** [comment]
Hmm could be the secure flag (which will be fixed by #1270) when accessed over http.
Does it work when you set https://github.com/engelsystem/engelsystem/blob/e11b0db/src/Http/SessionServiceProvider.php#L61 to `false`?

**Comment by chipuni** [comment]
Thank you, @MyIgel !

That solved my problem!

You are an angel!

**Comment by MyIgel** [comment]
The fix has been merged to main ( https://github.com/engelsystem/engelsystem/commit/23de3579af9e2347ac1ba62032378d0c73eee402#diff-94e013b92674cfca3d0ba9caee187aaf21c35ae744d184b65fc513dfe7af7740R63 ) @chipuni / @felixfrischeisen, can you test if that works for you?

**Comment by felixfrischeisen** [comment]
Thank you so much! The pain is over!
<img width="1435" alt="image" src="https://github.com/engelsystem/engelsystem/assets/49589035/0210402d-7175-4006-a16b-c5260f55ab0c">

**Comment by MyIgel** [comment]
Happy to hear that, i'll close the issue then :)
