### ISSUE TITLE
make app caluclate number of vouchers an angel is eligable for

### ISSUE THREAD

**Issue by tike** [engelsystem/engelsystem#242]
Hi,

when giving out vouchers to angels at the heaven front desk, front-desk angels currently have to manually check wether and how many vouchers an angel is eligable for. This is  a rather tedious manual process involving manually parsing the eligable angel's shift table. This draws unnecessarily on both time and brain power of front-desk angels.

As this is a very common operation, done several times per event and angel and angels tend to pile up in bulk to request new vouchers before lunch times, automating would help quite a bit in handling those peaks.

I'd volunteer to implement a feature, so the number of  vouchers an angel is currently eligable for is calculated (and displayed) by the app.

However, I wanted to consult with you before starting feature implementation, so please inform me of any doubts/concerns you might have.

Thanks!

**Comment by msquare** [comment]
Hi,

nice idea. I'd like to have a configuration option (config.php) to specify the number of shifts that lead to a number of vouchers and the basic amount of vouchers given to an arrived angel. On this base you can display the eligable number on the "edit user vouchers" view.

Don't limit the input to that number, just display it. (Because there are many vouchers given to special people)

So, these are my ideas/concers. I'm looking forward to your pullrequest containing this feature.

Thanks!

**Comment by tike** [comment]
Thanks for your feedback.

Regarding your ideas/suggestions: That's pretty much exactly how I intended to build it ;-)

I'll get back with a PR or questions regarding the codebase, if I get stuck.

**Comment by msquare** [comment]
Merged now :+1:
