### ISSUE TITLE
"Everlasting" Events (continuous planning of people supporting other people)

### ISSUE THREAD

**Issue by kakohari** [engelsystem/engelsystem#288]
Hi all,
is it possible to create an event which is somehow everlasting?
The idea is to manage people (and their skills) who support other people, e.g. refugees assisted by volunteers. This is not something like a congress or camp, as it has no fixed end date (well, except someone is declaring a new end of the world, and except some astrological issues, but I don't care about the latter...)
There might be events which are typical recurring, like picking someone up and help them to understand what the doctor says or what the should do or something like that. That event might be scheduled weekly.
Is the engelsystem the right tool? Or a starting point to fork?

**Comment by msquare** [comment]
Hi,
since the engelsystem is meant for ending events, there is no possibility to manage your requirements in an efficient way with this system. Maybe try a groupware including calendars and todos or a ticketsystem with recurring ticket support.
There is an engelsystem fork for refugee work on https://github.com/muccc/engelsystem which should be your starting point for a fork, because they changed some features to be less chaos like (things like DECT phone number).

**Comment by jschpp** [comment]
Just out of curiosity. Is it possible to set the end date to for example year 3000?

**Comment by msquare** [comment]
Yes, this is possible, but then the shift calender view would explode since the shift will have a height of more than 700.000.000px, containing multiple millions of html-elements. Also you can only join one shift at a time.

**Comment by msquare** [comment]
I tried this. Was not funny.

**Comment by jschpp** [comment]
Hmm... But that could be a problem in general. Maybe you should paginate the view after a length of x days.
