### ISSUE TITLE
Can only enter driving license info if link is known

### ISSUE THREAD

**Issue by sixtyfive** [engelsystem/engelsystem#378]
#198 works fine as long as you know about https://engelsystem.de/34c3/user-driver-licenses, but there's no link from either https://engelsystem.de/34c3/users?action=view or https://engelsystem.de/34c3/user-settings to the driving licenses page.

**Comment by msquare** [comment]
Since we dont want to collect data that is not needed, the links to the user driver licence pages will show up only if you joined an angeltype which requires a driving licence. They come as hint in the navbar as well as link on the angeltype page which has the requirement.
For now this works as intended and will not be changed.
