### ISSUE TITLE
htmlentities-like content in a comment gets removed

### ISSUE THREAD

**Issue by jens1o** [engelsystem/engelsystem#510]
see https://engelsystem.de/35c3/news-comments?nid=1

I entered `+1 for Mastodon (missing reactions here)` instead of `1 for Mastodon (missing reactions here)`.

I used Firefox Nightly `65.0a1 (2018-12-03) (64-bit)` on Arch Linux.

**Comment by jens1o** [comment]
according to @MyIgel it looks like actually more things are removed, not just trimmed off at both sides.

**Comment by msquare** [comment]
Oh. It was not intended to strip + chars.

**Comment by MyIgel** [comment]
I think this functionality should be fixed.. Why not encode the text with htmlentities and maybe also allow markdown?

**Comment by jens1o** [comment]
I can recommend Parsedown for parsing markdown, and it is extremly fast.

**Comment by MyIgel** [comment]
Thats what we are already [using](https://github.com/engelsystem/engelsystem/blob/master/composer.json#L25) for news and other text fields ;)

**Comment by der-michik** [comment]
> Thats what we are already [using](https://github.com/engelsystem/engelsystem/blob/master/composer.json#L25) for news and other text fields ;)

For news? Are you sure? I had some struggle with the markup when posting news earlier today because I assumed it was Markdown like angel and shift type descriptions. I then [found out](https://github.com/engelsystem/engelsystem/blob/master/includes/pages/admin_news.php#L64) that it is just plaintext with an optional `strip_tags`. However, the regex is only in place for comments.

Wouldn't it be a good idea to unify all this and have uniform behaviour for user input everywhere? Just use Markdown for angel type and shift type descriptions and news entries. Maybe limit the subset for news comments (if the parser can do that) to simple formatting like lists, bold and italic but strip links, images and headlines.

In addition: I understand where the special `admin_news_html` permission comes from historically, but is that really needed now where most stuff is Markdown anyway?

**Comment by MyIgel** [comment]
Oh, äh jup, not for news :(

The usecase is (and wah) that its easier to format tables in html than in markdown -> so its a convenience factor according to @msquare (and thats the reason why i haven't removed it jet)
