### ISSUE TITLE
Optional pronoun statement

### ISSUE THREAD

**Issue by benjaminwand** [engelsystem/engelsystem#593]
Nicknames mostly aren't gender specific. In order to help reduce misgendering transgendered angles, there could be a *pronoun* dropdown field. I'd suggest these options: "he", "she", "they" and "don't tell", with "don't tell" as default. And then the pronoun would appear behind the nick name if it is not "don't tell". 
Like that:
Tiger08 (he)
aLEx (she)
oh:my (they)
Willi
where "Willi" clicked "don't tell" or didn't touch the field at all.

**Comment by MyIgel** [comment]
Would that be enough? I mean there are many more options here as the ones stated above so we would need some kind of text field, but that would introduce the issue how to translate them.

-> Needs further discussion

**Comment by benjaminwand** [comment]
OK, indeed, text field would be better.

**Comment by DarkGigaByte** [comment]
+1 for text field

**Comment by cyriax0** [comment]
I feel like collecting data about gender is not the hacker way ("Datensparsamkeit").
Also I don't want anyone to feel compelled to gender oneself and I think introducing a gender/pronoun field would be highly controversial (I expect at least a moderate shitstorm).
Changing a currently gender neutral system into a gendered system would be counterproductive to weakening the influence gender has.

Maybe a universal "communication hints" field would allow for pronouns to be specified without changing our system to be explicitly gendered.
Additionally it could provide other useful information like preferred languages or HoH/deaf status as well as pronouns.
But I'm not sure if that would really help as usually communication starts before I look up an angel in the engelsystem.

**Comment by MIntrovrt** [comment]
I like the Idea of an universal "communication hints" field.
+1

**Comment by DarkGigaByte** [comment]
An optional text field for preferred pronouns does not make a system "explicitly gendered". I can still enter non-binary pronouns or nothing at all.

I agree that a universal "communication hints" is a nice idea, but with a dedicated and kinda short field we could display preferred pronouns more prominently whereever the nickname is displayed and there is not much space for a bigger text. (e.g.: angel list column & account detail page heading)

If we do this the shift coordinators at heaven could use the right pronouns from the beginning of the conversation.

**About the "Datensparsamkeit":** There is a need for the use of preferred pronouns at the events. (Okay, not just at the events, but in general...)
At camp19 i talked with some people from the awareness team about this issue (not the github one) and they said that it would be great to have them inside the engelsystem and on the angelbadges.
Since then i try to make both happen by talking to various people about it, as it is also a personal issue for me.

**How about we do both fields?**
One short(15 chars max) optional single-line text field for the preferred pronouns and one long optional multi-line text field for communication hints. And also 2 config flags to disable the display of these fields for events that does not want to use them.

**Comment by benjaminwand** [comment]
Both text fields sound good to me

**Comment by MIntrovrt** [comment]
I agree. Let's have both

**Comment by cyriax0** [comment]
I don't like the idea that collecting pronouns is the default for a tool. If firefox or gcc would ask me for a pronoun first, I'd feel that removing such a feature would "fix" it. Also communication as a shift coordinator usually starts before I look up somebody in the system so I have usually have to ask/guess first. Nontheless there is a big enough trans community where the right prononus are fought for hard that the total benefit on Chaos events would be bigger than it's drawbacks.

If there is an implementation of a pronoun feature, it shouldn't be the default as I don't wan't communties to feel compellt to collect such data. Otherwise giving more options to communities is good.

**Comment by nemobis** [comment]
The main issue are usually strings which require knowledge of the user's grammatical gender to be correctly translated, see https://translatewiki.net/wiki/Gender for some examples. In https://github.com/engelsystem/engelsystem/blob/master/resources/lang/en_US/additional.po I see "You have to confirm your password" which may be one example for some languages (not in Italian, although it might have been with a different wording: cf. https://translatewiki.net/w/i.php?title=Special:Translations&message=MediaWiki%3AFlow-dialog-cancelconfirm-title%2Fit ).
