### ISSUE TITLE
Feature: Rides and Lifts organization

### ISSUE THREAD

**Issue by konsumate** [engelsystem/engelsystem#615]
# Summary
At a @c3sustainability Meetup during the GPN19, the idea was raised to have sustainable ways of having people arrive/depart from the event by making it more easy to organize rides and lifts from/to the event with structures inside the angel system - another nice bonus point is that people who are only on the lookout for rides and lifts will take notice of the angel possibilities of an event (if coupled with the angel system).

## Preliminary solution draft

Ease up the process of organizing rides and lifts directly during the registration or payment process, while indicating the following data:
* what region they will be departing from
* a possible date corridor
* What travel resources they have (car, bus, ship, helicopter, )
* what capacity their travel resource have (ie. numbers of seats)

A pathing and routing algorithm should be able to come up with a decent proposal of efficient routes and capacity management based on the data given. People could confirm a few days/weeks before the event their route/ride. 

There is probably more to it - feedback welcomed

**Comment by MyIgel** [comment]
That sounds more like an own application (with integration) than a core feature :D

**Comment by herzmut** [comment]
It basically exists as "BerlKönig" in Berlin. 😄

**Comment by msquare** [comment]
I agree with @MyIgel. Ride organization does not match with "shift planning system". This topic may become very complex very quickly. We may discuss an auth and api integration to an existing ride planning system.

**Comment by fnrk** [comment]
There was a session the Camp https://events.ccc.de/camp/2019/wiki/Session:C3Sus_Ride_excellent_with_each_other and further conversion will be in https://rocket.events.ccc.de/channel/c3ride

**Comment by cyriax0** [comment]
There was a limited ride organization at the 35c3 buildup from and to hostels. It was discontinued at 36c3 because of social reasons (people started demanding rides/more capacity). If you want basic functionality ask the LOC for their prototype.

Any shared ride service shouldn't be "official", shouldn't limited to Angels, and shouldn't be volunteering (but something participants do). If an event needs volunteer drivers there are shift types with driving license requirement for that. Otherwise this is out of scope for the engelsystem.

I believe this issue should be closed / rejected.
