### ISSUE TITLE
logout on Sarfari with iPhone SE (old) not working

### ISSUE THREAD

**Issue by xuwhite** [engelsystem/engelsystem#792]
The logout button does not work using safari on iPhone SE (old). It also would be nice if its possible to scroll down the menu a bit further, to reach the button more easily.
@marudor can you please have a look at it.

**Comment by marudor** [comment]
I've looked into it. The problem is that ne navbar is rendered outside of the original container it is in. iOS is bad at those renderings. For that bottom navbar iOS has it needs to know the height. If you move the navbar to the body (and when it has `height: calc( 100% - @navbar-height);` it will work. But that will break other layouts.
I'm not experienced enough with all the layouts the engelsystem has to easily change that.

**Comment by MyIgel** [comment]
There are not that many variations (mainly the "wide" used on the shifts view and the "container" which normally is used). The menu itself only changes to the side menu on smaller devices and that should be it?

All other bugs are the problem of the reviewing/merging person ;)
